apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/rbac-role.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/alb-ingress-controller.yaml
patchesStrategicMerge:
- deployment.yaml
