services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD
    volumes:
    - ./initdb.d:/docker-entrypoint-initdb.d
    expose:
    - 5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: YOUR_PGADMIN_PASSWORD
    ports:
    - 8000:80
