resources:
- airflow.yaml
- volumes.yaml
# - postgres.yaml
configMapGenerator:
- name: airflow-configmap
  files:
  - configmap/airflow.cfg
- name: airflow-git-sync-known-hosts
  files:
  - configmap/known_hosts
secretGenerator:
- name: airflow-secrets
  literals:
  - sql_alchemy_conn=postgresql+psycopg2://root:root@postgres-airflow:5432/airflow
- name: airflow-git-sync-ssh-key
  files:
  - secret/github_shibataka000
